name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ashishgupta251
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark

      - name: Create output branch and push files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Create / switch to output branch
          git checkout -B output

          # Make output folder
          mkdir -p output

          # Move generated SVG files to output folder
          mv snake.svg output/github-contribution-grid-snake.svg
          mv snake-dark.svg output/github-contribution-grid-snake-dark.svg

          git add output/
          git commit -m "Update snake contribution animation" || echo "No changes"

          # Force push output branch
          git push -f origin output
